# Generated by Django 4.1.7 on 2023-03-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Car name')),
                ('img', models.ImageField(upload_to='car_images', verbose_name='Car image')),
                ('price', models.PositiveBigIntegerField(verbose_name='Car price')),
            ],
        ),
    ]
