# Generated by Django 4.1.7 on 2023-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80, verbose_name='User name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User email')),
                ('user_review', models.TextField(verbose_name='User review')),
            ],
        ),
    ]
